[tool.bumpversion]
allow_dirty = true
commit = true
commit_args = ""
current_version = "0.10.0-beta.1"
ignore_missing_files = false
ignore_missing_version = false
message = "Bump version: {current_version} → {new_version}"
parse = """(?x)
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
    (?:-(?P<pre_l>[a-zA-Z-]+)\\.(?P<pre_n>0|[1-9]\\d*))?
"""
regex = false
replace = "{new_version}"
search = "{current_version}"
serialize = [
  "{major}.{minor}.{patch}-{pre_l}.{pre_n}",
  "{major}.{minor}.{patch}",
]
sign_tags = false
tag = true
tag_message = "Bump version: {current_version} → {new_version}"
tag_name = "v{new_version}"

[tool.bumpversion.parts.pre_l]
optional_value = "final"
values = ["beta", "final"]

[[tool.bumpversion.files]]
filename = "node/package.json"
replace = "\"version\": \"{new_version}\","
search = "\"version\": \"{current_version}\","

[[tool.bumpversion.files]]
filename = "nodejs/package.json"
replace = "\"version\": \"{new_version}\","
search = "\"version\": \"{current_version}\","

# nodejs binary packages
[[tool.bumpversion.files]]
glob = "nodejs/npm/*/package.json"
replace = "\"version\": \"{new_version}\","
search = "\"version\": \"{current_version}\","

# Cargo files
# ------------
[[tool.bumpversion.files]]
filename = "rust/ffi/node/Cargo.toml"
replace = "\nversion = \"{new_version}\""
search = "\nversion = \"{current_version}\""

[[tool.bumpversion.files]]
filename = "rust/lancedb/Cargo.toml"
replace = "\nversion = \"{new_version}\""
search = "\nversion = \"{current_version}\""

# Java files
# Consider using mvn version management if java project becomes more complex
# ------------
[[tool.bumpversion.files]]
glob = "java/pom.xml"
replace = """
    <groupId>com.lancedb</groupId>
    <artifactId>lancedb-parent</artifactId>
    <version>{new_version}</version>
"""
search = """
    <groupId>com.lancedb</groupId>
    <artifactId>lancedb-parent</artifactId>
    <version>{current_version}</version>
"""

[[tool.bumpversion.files]]
glob = "java/*/**/pom.xml"
replace = """
        <groupId>com.lancedb</groupId>
        <artifactId>lancedb-parent</artifactId>
        <version>{new_version}</version>
"""
search = """
        <groupId>com.lancedb</groupId>
        <artifactId>lancedb-parent</artifactId>
        <version>{current_version}</version>
"""
